# Generated by Django 3.2 on 2021-06-05 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(default='No description yet.')),
                ('deadline', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('deadline', models.DateTimeField()),
                ('front_end', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
                ('late', models.BooleanField(default=False)),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='spot.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userstasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
