# Generated by Django 3.2 on 2021-06-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0003_alter_event_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
